-- lock_wait_sampler.sql — 5 Hz pg_locks sampler for the P0 G7/G8 baseline, plus the
-- positive control that proves it can see anything at all.
--
-- This file produced the pg_locks half of the published P0 G7/G8 lock-wait baselines
-- for the runs the report calls `bulk-10 v2` and `bulk-50 v2`, and for those two only
-- (measured 2026-09-07). Three earlier published runs -- interactive-10, interactive-50
-- and `bulk-10 fenced` (the run with http_409=309, which is NOT the `bulk-10 v1` kept
-- for comparison) -- came from the iteration afflicted by defects 2 and 3 below, and
-- `bulk-10 v1` / `bulk-50 v1` from the iteration afflicted by defect 3. None of those
-- five is reproducible by this corrected query, and for the two interactive runs the
-- server log -- not the sampler -- is the trustworthy lock-wait evidence. It took
-- THREE iterations to become an instrument instead of a decoration, and it lived only
-- as a scratch file on a staging host that has since been wiped. It is committed here
-- so the next person inherits the working version and the three traps, rather than
-- re-deriving all of them.
--
-- What it measures: how many backends in this database are waiting on a lock right
-- now, sampled every 200 ms. It complements the PostgreSQL log, which only records a
-- wait once it exceeds deadlock_timeout — a 100 ms observation floor in the baseline
-- runs. Waits shorter than that exist only here.
--
-- ============================================================================
-- THREE DEFECTS FOUND IN THIS SAMPLER. ALL THREE PRODUCED THE IDENTICAL OUTPUT:
--   samples_with_waiter = 0
-- NONE OF THEM WAS SELF-REVEALING. Each looked exactly like a healthy, uncontended
-- system, and two of them were believed for a full round of measurements.
-- ============================================================================
--
-- DEFECT 1 — TIMING. The sampler is started before the load, so it must still be
-- running while the load runs. In the first pass it was launched with a command that
-- did not return when it appeared to, and the harness spends ~72 s enrolling devices
-- before it emits a single request; the sampler had already exited when the load
-- began. Overlap was 0 seconds. Its zeros described an idle system, truthfully, and
-- were read as "no contention under load". Mitigation: launch the sampler in the
-- SAME command as the load with a fixed delay, and afterwards check the first and
-- last clock_timestamp() in the output against the load window. Do not assume overlap
-- — compute it.
--
-- DEFECT 2 — PREDICATE. The original filter was:
--     WHERE NOT l.granted AND l.relation = 'site_change_counters'::regclass
-- Row-level contention does not appear as a lock on the relation. A backend blocked
-- on a row already locked by another transaction waits on ShareLock on transactionid,
-- and for that locktype pg_locks.relation IS NULL. NULL = <oid> is NULL, never true,
-- so row-level contention was STRUCTURALLY invisible: 26 of the 27 waits the server
-- log recorded in that window could not have matched the predicate under any load.
-- Mitigation: do not filter by relation. Count every ungranted lock in this database
-- and let the server log attribute it to an object.
--
-- DEFECT 3 — LOOP STRUCTURE. This one survived the fix for defect 2 and is the
-- subtlest of the three. The sampler looped with generate_series and pg_sleep(0.2),
-- carrying the two measurements as uncorrelated scalar subqueries in the target list.
-- Because those subqueries do not reference the series, the planner hoists them into
-- InitPlans, which are evaluated ONCE before the first row is emitted:
--     Function Scan on generate_series
--       InitPlan 1 (returns $0)  ->  Aggregate  ->  Hash Join ... pg_lock_status ...
--       InitPlan 2 (returns $1)  ->  Aggregate  ->  Hash Join ... pg_lock_status ...
-- clock_timestamp() and pg_sleep() are volatile and DO re-run per row, so the output
-- had 700 rows with a plausibly advancing timestamp and the correct wall-clock span.
-- It looked like 700 samples. It carried ONE, taken before the load started. The
-- giveaway that nobody looked for: 700 rows of exactly 0|0 with no variance at all.
--   A RELATED TRAP, avoided by the same fix: pg_stat_activity is cached per
--   transaction (pgstat_read_current_status()), so ANY loop that stays inside one
--   transaction — including a PL/pgSQL DO block, which is the obvious "fix" for the
--   InitPlan problem — re-reads the same frozen snapshot and reproduces the identical
--   symptom for a completely different reason.
-- Mitigation: \watch. Each iteration is a separate statement in its own implicit
-- transaction, which defeats both the InitPlan hoist and the stats cache.
--
-- ============================================================================
-- MANDATORY: ANY future use of this sampler MUST run the positive control in
-- section 2 alongside it. Three independent defects in one instrument all reported
-- "no contention", and no amount of reading the SQL distinguished a quiet system
-- from a blind one. A zero from this sampler means nothing unless a control run in
-- comparable conditions returns non-zero. The control uses advisory locks only and
-- touches no table data.
-- ============================================================================
--
-- Requires psql 16+ for the named \watch parameters (postgres:16-alpine in
-- docker-compose.yml). On psql 15 and older, use bare `\watch 0.2` -- the sampler
-- query is unchanged. Note that bare \watch never terminates on its own; in a `-f -`
-- pipeline there is no terminal to interrupt it, and timeout(1) kills the local client
-- without necessarily killing the psql process inside the container. Confirm the
-- container-side process has exited before treating the run as complete.


-- ============================================================================
-- SECTION 1 — THE SAMPLER (this is what `psql -f` runs)
-- ============================================================================
-- 700 samples x 200 ms = 140 s, which covers a 120 s load run with margin at both
-- ends. Run it against the same database the load is hitting:
--
--   docker compose --env-file <env> exec -T postgres \
--     psql -U <db_user> -d <db_name> -At -F"|" -f - < lock_wait_sampler.sql \
--     > /tmp/lockwait-<label>.log 2>&1
--
-- Aggregate afterwards (samples | samples_with_waiter | max statement age | max wait):
--
--   awk -F'|' 'NF>=4 {n++; if ($2+0 > 0) w++; if ($3+0 > s) s=$3+0; if ($4+0 > m) m=$4+0} \
--              END {print "samples="n+0, "samples_with_waiter="w+0, \
--                         "max_stmt_age_ms="s+0, "max_wait_ms="m+0}' \
--     /tmp/lockwait-<label>.log
-- The NF>=4 guard skips lines that do not have four pipe-delimited fields. TWO
-- INDEPENDENT sources produce such lines: psql's own command tag for the SET below, and
-- anything on stderr that 2>&1 merges into the same file (notices, errors). Either one
-- increments n without the guard; do not collapse them into one mechanism. It was NF>=3
-- while the query had three columns -- a log from an older run needs the older guard.
--
-- Three published runs report samples=701 against a 700-iteration sampler: interactive-10,
-- interactive-50, and `bulk-10 fenced` (http_409=309, the run the P0 report discards --
-- NOT `bulk-10 v1`). All three are from the generate_series iteration and none used
-- \watch, so 701 never meant "701 samples were taken". The two \watch runs (bulk-10 v2,
-- bulk-50 v2) are published as 700 samples, but their aggregator output was never
-- captured verbatim and the sampler file they ran from was deleted, so whether their raw
-- log held 700 or 701 lines is an OPEN QUESTION -- see the P0 report, label 8. No verdict
-- turns on it: samples_with_waiter and the max columns are unaffected either way, because
-- a short line coerces its empty fields to 0.
--
-- Reading the columns honestly:
--   waiting          number of backends in this database holding an UNGRANTED lock at the
--                    instant of the sample. Excludes this sampler's own backend.
--   max_stmt_age_ms  clock_timestamp() - query_start, i.e. the AGE OF THE STATEMENT, not
--                    the age of the wait. A statement can run for a while before it starts
--                    waiting, so this is an UPPER BOUND on wait time and will read higher
--                    than the server log's figure for the same event. That is consistent,
--                    not contradictory. A 0.0 means the sample caught a waiter in the
--                    instant its statement began. THIS is the column the P0 report
--                    published under the name max_wait_ms; it was the only one that
--                    existed then, and the name overstated what it measured.
--   max_wait_ms      clock_timestamp() - pg_locks.waitstart, i.e. the ACTUAL AGE OF THE
--                    WAIT. waitstart has existed since PostgreSQL 14 and this stack is
--                    postgres:16-alpine, so it was available for the P0 runs and simply
--                    was not used -- the P0 baseline bounds metric 1 instead of measuring
--                    it for want of this one column. Unlike the server log, it has no
--                    100 ms floor. Caveat from the PostgreSQL docs: waitstart can be NULL
--                    for a very short interval after a wait begins even though granted is
--                    false, so a sample that lands in that interval contributes 0 here
--                    while still counting in `waiting`.
--
-- Both columns are kept: max_stmt_age_ms is what the four published P0 baselines contain,
-- so dropping it would make the next run incomparable with them field-by-field, and their
-- ratio is itself informative (how much of a statement's life was spent waiting).
--
-- THE LIMIT THAT SURVIVES BOTH COLUMNS: at 5 Hz this is a SAMPLE of waits, not a census,
-- and a length-biased one -- a wait is observed with probability proportional to its
-- duration, so short waits are systematically under-represented and a wait shorter than
-- 200 ms can be missed entirely. Counts from this sampler are not incidence counts, and
-- max over samples is a LOWER bound on the true maximum wait. A p50/p95 of wait duration
-- still needs the server log (floored at deadlock_timeout) or a census instrument.
--
-- statement_timeout is disabled as a precaution. Under \watch each iteration is its own
-- sub-millisecond statement in its own implicit transaction, so statement_timeout would
-- not be triggered by normal sampler operation; the SET is kept as a safeguard.
SET statement_timeout = 0;
\pset title ''
SELECT clock_timestamp() AS ts,
       (SELECT count(*) FROM pg_locks l JOIN pg_stat_activity a USING (pid)
         WHERE NOT l.granted AND a.pid <> pg_backend_pid() AND a.datname = current_database()) AS waiting,
       (SELECT coalesce(max(EXTRACT(epoch FROM clock_timestamp() - a.query_start) * 1000), 0)
          FROM pg_locks l JOIN pg_stat_activity a USING (pid)
         WHERE NOT l.granted AND a.pid <> pg_backend_pid() AND a.datname = current_database()) AS max_stmt_age_ms,
       (SELECT coalesce(max(EXTRACT(epoch FROM clock_timestamp() - l.waitstart) * 1000), 0)
          FROM pg_locks l JOIN pg_stat_activity a USING (pid)
         WHERE NOT l.granted AND a.pid <> pg_backend_pid() AND a.datname = current_database()) AS max_wait_ms
\watch i=0.2 c=700


-- ============================================================================
-- SECTION 2 — POSITIVE CONTROL (MANDATORY, run alongside section 1)
-- ============================================================================
-- Why this is a shell block and not more SQL in this file: a positive control needs
-- real lock contention, which needs at least two CONCURRENT sessions plus the sampler
-- as a third. One `psql -f` script is one session, so it cannot manufacture the
-- condition it is meant to detect. Copy the block below, strip the leading `-- `, and
-- fill in the three placeholders.
--
-- It is safe on a live database: pg_advisory_lock uses the same single-bigint advisory
-- key space as the application (RetentionRepository.cs takes a single-argument
-- pg_try_advisory_xact_lock). A key collision is astronomically unlikely (~1-in-2³²)
-- and harmless if it occurs: the application's lock is a non-blocking try, so a
-- collision costs one skipped retention pass at most. The control reads or writes NO
-- table data.
-- The holder releases after 9 s and both sessions exit.
--
-- Expected result, and the whole point: the corrected sampler reports a non-zero
-- samples_with_waiter, and max_wait_ms climbs roughly linearly while the waiter is
-- blocked. When this control was run against both versions under identical
-- conditions, the original generate_series sampler saw 0 of 60 samples and the
-- \watch sampler saw 35 of 60 — from the same contention, at the same moment.
-- IF THE CONTROL RETURNS ZERO, THE SAMPLER IS BLIND AND EVERY ZERO IT PRODUCED IN
-- THAT SESSION IS UNINTERPRETABLE. Fix the instrument before reporting anything.
--
-- ----------------------------------------------------------------------------
-- PSQL='docker compose --env-file <env> exec -T postgres psql -U <db_user> -d <db_name>'
-- KEY=918273645          # arbitrary; any bigint the application never uses
--
-- # session A — holds the advisory lock for 9 s
-- $PSQL -At -c "SELECT pg_advisory_lock($KEY);" \
--              -c "SELECT pg_sleep(9);" \
--              -c "SELECT pg_advisory_unlock($KEY);" &
--
-- # session C — the sampler under test, 60 samples x 200 ms = 12 s, started now so it
-- #             is already running when the waiter blocks. Fed on stdin, not with -c:
-- #             \watch re-runs the previous query buffer, which a separate -c does not
-- #             leave behind.
-- $PSQL -At -F"|" -f - > /tmp/pc-sampler.log 2>&1 <<'SQL' &
-- <paste the SET / \pset / SELECT ... \watch query from section 1 here verbatim,
--  replacing \watch i=0.2 c=700 with \watch i=0.2 c=60>
-- SQL
--
-- # session B — asks for the same key ~2 s later and blocks until A releases
-- sleep 2
-- $PSQL -At -c "SELECT pg_advisory_lock($KEY);" -c "SELECT pg_advisory_unlock($KEY);"
-- wait
--
-- awk -F'|' '{n++; if ($2+0 > 0) w++} END {print "samples="n+0, "samples_with_waiter="w+0}' \
--   /tmp/pc-sampler.log
-- # PASS: samples_with_waiter is clearly non-zero (~35 of 60 for a ~7 s block)
-- # FAIL: 0 — the instrument is blind; do not report any lock conclusion from it
-- ----------------------------------------------------------------------------
--
-- Housekeeping: /tmp/lockwait-*.log and /tmp/pc-sampler*.log are run artefacts. Copy
-- the aggregated numbers into the report, then delete them; do not leave sampler
-- output on a shared host.
